/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Condition = { 'Fair' : null } |
  { 'Good' : null } |
  { 'Mint' : null } |
  { 'Poor' : null } |
  { 'NearMint' : null } |
  { 'Excellent' : null };
export interface PortfolioSnapshot { 'totalValue' : number, 'date' : Timestamp }
export interface PortfolioStats {
  'totalValue' : number,
  'totalCards' : bigint,
  'gainLoss' : number,
  'totalCost' : number,
}
export interface PriceEntry {
  'id' : bigint,
  'date' : Timestamp,
  'note' : [] | [string],
  'estimatedValue' : number,
  'cardId' : bigint,
}
export interface SportCard {
  'id' : bigint,
  'purchasePrice' : number,
  'owner' : UserId,
  'team' : string,
  'year' : bigint,
  'currentValue' : number,
  'sport' : string,
  'notes' : [] | [string],
  'playerName' : string,
  'dateAdded' : Timestamp,
  'condition' : Condition,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'addCard' : ActorMethod<
    [string, string, string, bigint, Condition, number, number, [] | [string]],
    bigint
  >,
  'addPriceEntry' : ActorMethod<[bigint, number, [] | [string]], bigint>,
  'deleteCard' : ActorMethod<[bigint], boolean>,
  'getCard' : ActorMethod<[bigint], [] | [SportCard]>,
  'getCards' : ActorMethod<[], Array<SportCard>>,
  'getPortfolioHistory' : ActorMethod<[], Array<PortfolioSnapshot>>,
  'getPortfolioStats' : ActorMethod<[], PortfolioStats>,
  'getPriceHistory' : ActorMethod<[bigint], Array<PriceEntry>>,
  'updateCard' : ActorMethod<
    [bigint, string, string, string, bigint, Condition, number, [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];