/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Condition = IDL.Variant({
  'Fair' : IDL.Null,
  'Good' : IDL.Null,
  'Mint' : IDL.Null,
  'Poor' : IDL.Null,
  'NearMint' : IDL.Null,
  'Excellent' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const SportCard = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Float64,
  'owner' : UserId,
  'team' : IDL.Text,
  'year' : IDL.Nat,
  'currentValue' : IDL.Float64,
  'sport' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'playerName' : IDL.Text,
  'dateAdded' : Timestamp,
  'condition' : Condition,
});
export const PortfolioSnapshot = IDL.Record({
  'totalValue' : IDL.Float64,
  'date' : Timestamp,
});
export const PortfolioStats = IDL.Record({
  'totalValue' : IDL.Float64,
  'totalCards' : IDL.Nat,
  'gainLoss' : IDL.Float64,
  'totalCost' : IDL.Float64,
});
export const PriceEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : Timestamp,
  'note' : IDL.Opt(IDL.Text),
  'estimatedValue' : IDL.Float64,
  'cardId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCard' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Condition,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addPriceEntry' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteCard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCard' : IDL.Func([IDL.Nat], [IDL.Opt(SportCard)], ['query']),
  'getCards' : IDL.Func([], [IDL.Vec(SportCard)], ['query']),
  'getPortfolioHistory' : IDL.Func([], [IDL.Vec(PortfolioSnapshot)], ['query']),
  'getPortfolioStats' : IDL.Func([], [PortfolioStats], ['query']),
  'getPriceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(PriceEntry)], ['query']),
  'updateCard' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Condition,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Condition = IDL.Variant({
    'Fair' : IDL.Null,
    'Good' : IDL.Null,
    'Mint' : IDL.Null,
    'Poor' : IDL.Null,
    'NearMint' : IDL.Null,
    'Excellent' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const SportCard = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Float64,
    'owner' : UserId,
    'team' : IDL.Text,
    'year' : IDL.Nat,
    'currentValue' : IDL.Float64,
    'sport' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'playerName' : IDL.Text,
    'dateAdded' : Timestamp,
    'condition' : Condition,
  });
  const PortfolioSnapshot = IDL.Record({
    'totalValue' : IDL.Float64,
    'date' : Timestamp,
  });
  const PortfolioStats = IDL.Record({
    'totalValue' : IDL.Float64,
    'totalCards' : IDL.Nat,
    'gainLoss' : IDL.Float64,
    'totalCost' : IDL.Float64,
  });
  const PriceEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : Timestamp,
    'note' : IDL.Opt(IDL.Text),
    'estimatedValue' : IDL.Float64,
    'cardId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCard' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Condition,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addPriceEntry' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteCard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCard' : IDL.Func([IDL.Nat], [IDL.Opt(SportCard)], ['query']),
    'getCards' : IDL.Func([], [IDL.Vec(SportCard)], ['query']),
    'getPortfolioHistory' : IDL.Func(
        [],
        [IDL.Vec(PortfolioSnapshot)],
        ['query'],
      ),
    'getPortfolioStats' : IDL.Func([], [PortfolioStats], ['query']),
    'getPriceHistory' : IDL.Func([IDL.Nat], [IDL.Vec(PriceEntry)], ['query']),
    'updateCard' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Condition,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };