/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface SportCard {
    id: bigint;
    purchasePrice: number;
    owner: UserId;
    team: string;
    year: bigint;
    currentValue: number;
    sport: string;
    notes?: string;
    playerName: string;
    dateAdded: Timestamp;
    condition: Condition;
}
export interface PortfolioStats {
    totalValue: number;
    totalCards: bigint;
    gainLoss: number;
    totalCost: number;
}
export interface PortfolioSnapshot {
    totalValue: number;
    date: Timestamp;
}
export interface PriceEntry {
    id: bigint;
    date: Timestamp;
    note?: string;
    estimatedValue: number;
    cardId: bigint;
}
export enum Condition {
    Fair = "Fair",
    Good = "Good",
    Mint = "Mint",
    Poor = "Poor",
    NearMint = "NearMint",
    Excellent = "Excellent"
}
export interface backendInterface {
    addCard(playerName: string, sport: string, team: string, year: bigint, condition: Condition, purchasePrice: number, currentValue: number, notes: string | null): Promise<bigint>;
    addPriceEntry(cardId: bigint, estimatedValue: number, note: string | null): Promise<bigint>;
    deleteCard(id: bigint): Promise<boolean>;
    getCard(id: bigint): Promise<SportCard | null>;
    getCards(): Promise<Array<SportCard>>;
    getPortfolioHistory(): Promise<Array<PortfolioSnapshot>>;
    getPortfolioStats(): Promise<PortfolioStats>;
    getPriceHistory(cardId: bigint): Promise<Array<PriceEntry>>;
    updateCard(id: bigint, playerName: string, sport: string, team: string, year: bigint, condition: Condition, purchasePrice: number, notes: string | null): Promise<boolean>;
}
import type { Condition as _Condition, PriceEntry as _PriceEntry, SportCard as _SportCard, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCard(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Condition, arg5: number, arg6: number, arg7: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, arg1, arg2, arg3, to_candid_Condition_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, arg1, arg2, arg3, to_candid_Condition_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async addPriceEntry(arg0: bigint, arg1: number, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPriceEntry(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPriceEntry(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteCard(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0);
            return result;
        }
    }
    async getCard(arg0: bigint): Promise<SportCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCard(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCard(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCards(): Promise<Array<SportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCards();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCards();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioHistory(): Promise<Array<PortfolioSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHistory();
            return result;
        }
    }
    async getPortfolioStats(): Promise<PortfolioStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioStats();
            return result;
        }
    }
    async getPriceHistory(arg0: bigint): Promise<Array<PriceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceHistory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceHistory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCard(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Condition, arg6: number, arg7: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, arg4, to_candid_Condition_n1(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, arg4, to_candid_Condition_n1(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_Condition_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Condition): Condition {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PriceEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceEntry): PriceEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SportCard_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SportCard): SportCard {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SportCard]): SportCard | null {
    return value.length === 0 ? null : from_candid_SportCard_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Timestamp;
    note: [] | [string];
    estimatedValue: number;
    cardId: bigint;
}): {
    id: bigint;
    date: Timestamp;
    note?: string;
    estimatedValue: number;
    cardId: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.note)),
        estimatedValue: value.estimatedValue,
        cardId: value.cardId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    purchasePrice: number;
    owner: _UserId;
    team: string;
    year: bigint;
    currentValue: number;
    sport: string;
    notes: [] | [string];
    playerName: string;
    dateAdded: _Timestamp;
    condition: _Condition;
}): {
    id: bigint;
    purchasePrice: number;
    owner: UserId;
    team: string;
    year: bigint;
    currentValue: number;
    sport: string;
    notes?: string;
    playerName: string;
    dateAdded: Timestamp;
    condition: Condition;
} {
    return {
        id: value.id,
        purchasePrice: value.purchasePrice,
        owner: value.owner,
        team: value.team,
        year: value.year,
        currentValue: value.currentValue,
        sport: value.sport,
        notes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.notes)),
        playerName: value.playerName,
        dateAdded: value.dateAdded,
        condition: from_candid_Condition_n8(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fair: null;
} | {
    Good: null;
} | {
    Mint: null;
} | {
    Poor: null;
} | {
    NearMint: null;
} | {
    Excellent: null;
}): Condition {
    return "Fair" in value ? Condition.Fair : "Good" in value ? Condition.Good : "Mint" in value ? Condition.Mint : "Poor" in value ? Condition.Poor : "NearMint" in value ? Condition.NearMint : "Excellent" in value ? Condition.Excellent : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SportCard>): Array<SportCard> {
    return value.map((x)=>from_candid_SportCard_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceEntry>): Array<PriceEntry> {
    return value.map((x)=>from_candid_PriceEntry_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Condition_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): _Condition {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): {
    Fair: null;
} | {
    Good: null;
} | {
    Mint: null;
} | {
    Poor: null;
} | {
    NearMint: null;
} | {
    Excellent: null;
} {
    return value == Condition.Fair ? {
        Fair: null
    } : value == Condition.Good ? {
        Good: null
    } : value == Condition.Mint ? {
        Mint: null
    } : value == Condition.Poor ? {
        Poor: null
    } : value == Condition.NearMint ? {
        NearMint: null
    } : value == Condition.Excellent ? {
        Excellent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
